# -*- coding: utf-8 -*-
simulationStartYear = 2020 #Simulaation aloitusvuosi
populationMultiplier = 0.01 #Populaation koko prosentuaalisena kertoimena
waistlineLargeRiskWomen = 1.0/4.0 #Vyötärömittä ylittää korkeamman riskipistearvon naisille 
waistlineLargeRiskMen = 1.0/4.0 #Vyötärömittä ylittää korkeamman riskipistearvon miehille
highBloodSugarRiskWomen = 19.0 #Korkean veren sokerin todennäköisyys naisille (raskaudenaikainen tilastotieto)
diabetesPrevalance = 15.5 #Diabeteksen mahdollisuus aloitushetkellä
diabetesDeathMultiplierWomen = 1.75 #Kuolemariskin kerroin naisdiabeetikoille
diabetesDeathMultiplierMen = 1.65 #Kuolemariskin kerroin miesdiabeetikoille
yearsPerIterationOfSimulation = 5 #Vuosien määrä mitä simuloidaan yhdessä simulaatiossa
consideredHighRisk = 20.0 #Korkean FINRISK-pisteytyksen raja
consideredRiskful = 12.0 #Riskissä olemisen FINRISK-pisteytyksen raja
highRiskHasPrediabetesWomen = 38.0 #Korkean pistemäärän saaneella naisella on prediabetes
highRiskHasPrediabetesMen = 49.0 #Korkean pistemäärän saaneella miehellä on prediabetes 
mediumRiskNoInterventionChance = 50.0 #Keskisuuren riskin henkilö ei aloita interventiota
highRiskNoInterventionChanceWomen = 5.0 #Korkean riskin nainen ei aloita interventiota
highRiskNoInterventionChanceMen = 10.0 #Korkean riskin mies ei aloita interventiota
digiAutoInterventionRatio = 2.0 #Suhdekerroin Digi-interventiona ja Autointerventioon sijoittuvista
interventionSieveCost = 1000.0 #Seulonnan kustannus 
interventionFollowUpYears = 3 #Kuinka monen vuoden ajan seurataan intervention jälkeen
processesToRun = ["f2f", "digi", "auto", "care", "followup"] #Ajettavat prosessit
interventionReassessmentPeriod = 3 #Arviointiperiodi interventioissa (kuukausia) 
followupReassessmentPeriod = 6 #Arviointiperiodi seurannannassa (kuukausia) 
f2fStartingCost = 70.0 #F2F-intervention aloituskustannukset / henkilö
digiStartingCost = 50.0 #Digi-intervention aloituskustannukset / henkilö
autoStartingCost = 30.0 #Autointervention aloituskustannukset / henkilö 
f2fRunningCost = 10.0 #F2F-intervention juoksevat kustannukset / kuukausi
digiRunningCost = 10.0 #DIgi-intervention juoksevat kustannukset / kuukausi 
autoRunningCost = 0.0 #Autointervention juoksevat kustannukset / kuukausi 
f2fReadjustmentCost = 20.0 #F2F-intervention uudelleenohjauksen kustannus
digiReadjustmentCost = 20.0 #Digi-intervention uudelleenohjauksen kustannus
f2fEndCounselingCost = 20.0 #F2F-intervention uudelleenohjauksen kustannus
digiEndCounselingCost = 20.0 #Digi-intervention uudelleenohjauksen kustannus
diabetesCareCost = 253.0 #Diabeteksen hoidon kustannus / kuukausi
followUpMonthlyCostPerPerson = 10.0 #Seurannan kustannus henkilöä kohdin / kuukausi 
followUpF2FAdditionalCounselingCost = 10.0 #Seurannan lisätuen kustannus F2F-interventiossa
followUpDigiAdditionalCounselingCost = 10.0 #Seurannan lisätuen kustannus Digi-interventiossa
followUpAutoAdditionalCounselingCost = 10.0 #Seurannan lisätuen kustannus Autointerventiossa
followUpDoctorVisitCost = 20.0 #Lääkärintarkastuksen hinta seurannassa
f2fReadjustmentChance = 100.0*(1.0-((1.0-(43.0/100.0)**(1.0/12.0)))) #F2F-intervention uudelleenohjauksen todennäköisyys
digiReadjustmentChance = 100.0*(1.0-((1.0-(32.0/100.0)**(1.0/12.0)))) #Digi-intervention uudelleenohjauksen todennäköisyys
autoReadjustmentChance = 100.0*(1.0-((1.0-(20.0/100.0)**(1.0/12.0)))) #Autointervention uudelleenohjauksen todennäköisyys
f2fEndCounselingChance = 100.0*(1.0-((1.0-(43.0/100.0)**(1.0/12.0)))) #F2F-intervention lopun ohjauksen todennäköisyys
digiEndCounselingChance = 100.0*(1.0-((1.0-(32.0/100.0)**(1.0/12.0)))) #Digi-intervention lopun ohjauksen todennäköisyys
f2fQuitChance = 100.0*(1.0-((1.0-(43.0/100.0)**(1.0/12.0)))) #F2F-intervention lopettamisen todennäköisyys
digiQuitChance = 100.0*(1.0-((1.0-(32.0/100.0)**(1.0/12.0)))) #Digi-intervention lopettamisen todennäköisyys
autoQuitChance = 100.0*(1.0-((1.0-(20.0/100.0)**(1.0/12.0)))) #Autointervention lopettamisen todennäköisyys
followUpF2FAdditionalCounselingChance = 54.0 #Lisätuen todennäköisyys F2F-intervention seurannassa 
followUpDigiAdditionalCounselingChance = 70.0 #Lisätuen todennäköisyys Digi-intervention seurannassa
followUpAutoAdditionalCounselingChance = 75.0 #Lisätuen todennäköisyys Autointervention seurannassa
simulationSaveFileName = "simuldata" #Simuloinnin tulostiedoston nimi

